"""Report generation: console summary, JSON, and standalone HTML."""

from __future__ import annotations

import html
import json
import os

from ..core.models import ScanResult, Severity

SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
                  Severity.LOW, Severity.INFO]

SEVERITY_COLORS = {
    "critical": "#7c1d1d",
    "high": "#c0392b",
    "medium": "#e67e22",
    "low": "#f1c40f",
    "info": "#3498db",
}


def _sorted_findings(result: ScanResult):
    rank = {s.value: i for i, s in enumerate(SEVERITY_ORDER)}
    return sorted(result.findings, key=lambda f: rank.get(f.severity.value, 99))


def write_json(result: ScanResult, path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(result.to_dict(), fh, indent=2)
    return path


def write_html(result: ScanResult, path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render_html(result))
    return path


def render_html(result: ScanResult) -> str:
    """Render the standalone HTML report as a string (used by CLI and web export)."""
    counts = result.counts_by_severity()

    rows = []
    for f in _sorted_findings(result):
        color = SEVERITY_COLORS.get(f.severity.value, "#777")
        rows.append(
            f"""
            <tr>
              <td><span class="badge" style="background:{color}">{html.escape(f.severity.value.upper())}</span></td>
              <td>{html.escape(f.type)}</td>
              <td class="mono">{html.escape(f.endpoint)}</td>
              <td>{html.escape(f.parameter or '-')}</td>
              <td>{html.escape(f.description)}</td>
              <td class="mono">{html.escape(f.payload or '-')}</td>
              <td class="mono">{html.escape(f.evidence or '-')}</td>
            </tr>"""
        )

    summary_chips = "".join(
        f'<span class="chip" style="background:{SEVERITY_COLORS[s.value]}">'
        f'{s.value.upper()}: {counts[s.value]}</span>'
        for s in SEVERITY_ORDER
    )

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WVS Report - {html.escape(result.target)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background:#f4f6f8; color:#222; }}
  header {{ background:#1f2d3d; color:#fff; padding:24px 32px; }}
  header h1 {{ margin:0 0 4px; font-size:20px; }}
  header .target {{ font-family:monospace; opacity:.85; }}
  .wrap {{ padding:24px 32px; }}
  .score {{ font-size:42px; font-weight:700; }}
  .chip, .badge {{ color:#fff; padding:3px 10px; border-radius:12px; font-size:12px; font-weight:600; display:inline-block; }}
  .chip {{ margin-right:8px; }}
  table {{ width:100%; border-collapse:collapse; background:#fff; box-shadow:0 1px 3px rgba(0,0,0,.1); border-radius:8px; overflow:hidden; }}
  th, td {{ text-align:left; padding:10px 12px; border-bottom:1px solid #eee; vertical-align:top; font-size:13px; }}
  th {{ background:#fafbfc; font-size:12px; text-transform:uppercase; letter-spacing:.04em; color:#555; }}
  .mono {{ font-family:monospace; word-break:break-all; max-width:280px; }}
  .meta {{ color:#666; font-size:13px; margin:8px 0 20px; }}
  .empty {{ padding:24px; background:#fff; border-radius:8px; }}
</style>
</head>
<body>
<header>
  <h1>Web Vulnerability Scan Report</h1>
  <div class="target">{html.escape(result.target)}</div>
</header>
<div class="wrap">
  <div class="score">Risk score: {result.risk_score}/100</div>
  <div class="meta">
    Crawled {result.pages_crawled} page(s) &middot; {len(result.findings)} finding(s)
    &middot; {html.escape(result.started_at)} &rarr; {html.escape(result.finished_at)}
  </div>
  <div style="margin-bottom:20px">{summary_chips}</div>
  {_table_or_empty(rows)}
  <p class="meta">Generated by WVS. For authorized testing only.</p>
</div>
</body>
</html>"""

    return doc


def _latin1(text: str) -> str:
    """Make text safe for fpdf2's core (latin-1) fonts."""
    if not text:
        return ""
    replacements = {
        "→": "->", "←": "<-", "—": "-", "–": "-",
        "‘": "'", "’": "'", "“": '"', "”": '"',
        "…": "...", "↑": "^", "↓": "v", "↗": ">",
        "·": "-", "•": "*",
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "replace").decode("latin-1")


def render_pdf(result: ScanResult) -> bytes:
    """Render the scan report as a PDF document (bytes). Requires fpdf2."""
    from fpdf import FPDF  # imported lazily so the CLI works without fpdf2

    rgb = {s.value: tuple(int(SEVERITY_COLORS[s.value][i:i + 2], 16) for i in (1, 3, 5))
           for s in SEVERITY_ORDER}
    counts = result.counts_by_severity()

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 9, "Web Vulnerability Scan Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 6, _latin1(f"Target: {result.target}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _latin1(f"Scanned: {result.started_at}  ->  {result.finished_at}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Pages crawled: {result.pages_crawled}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(2)
    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, f"Risk score: {result.risk_score}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    summary = "   ".join(f"{s.value.upper()}: {counts[s.value]}" for s in SEVERITY_ORDER)
    pdf.cell(0, 6, summary, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    if not result.findings:
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, "No findings reported.", new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    rank = {s.value: i for i, s in enumerate(SEVERITY_ORDER)}
    findings = sorted(result.findings, key=lambda f: rank.get(f.severity.value, 99))
    for i, f in enumerate(findings, 1):
        if pdf.get_y() > 255:
            pdf.add_page()
        r, g, b = rgb.get(f.severity.value, (120, 120, 120))
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(r, g, b)
        pdf.multi_cell(0, 6, _latin1(f"{i}. [{f.severity.value.upper()}] {f.type}"),
                       new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _latin1(f"Endpoint: {f.endpoint}"
                       + (f"   Parameter: {f.parameter}" if f.parameter else "")),
                       new_x="LMARGIN", new_y="NEXT")
        pdf.multi_cell(0, 5, _latin1(f"Description: {f.description}"),
                       new_x="LMARGIN", new_y="NEXT")
        if f.remediation:
            pdf.multi_cell(0, 5, _latin1(f"Remediation: {f.remediation}"),
                           new_x="LMARGIN", new_y="NEXT")
        if f.reference:
            ref = f.reference.replace(" | ", ": ")
            pdf.set_text_color(80, 80, 160)
            pdf.multi_cell(0, 5, _latin1(f"Reference: {ref}"),
                           new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.set_text_color(140, 140, 140)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 6, "Generated by WVS - for authorized testing only.",
             new_x="LMARGIN", new_y="NEXT")
    return bytes(pdf.output())


def _table_or_empty(rows: list) -> str:
    if not rows:
        return '<div class="empty">No findings. 🎉</div>'
    return f"""
    <table>
      <thead><tr>
        <th>Severity</th><th>Type</th><th>Endpoint</th><th>Param</th>
        <th>Description</th><th>Payload</th><th>Evidence</th>
      </tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>"""
