"""Report generation: console summary, JSON, and standalone HTML."""

from __future__ import annotations

import html
import json
import os

from ..core.models import ScanResult, Severity

SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
                  Severity.LOW, Severity.INFO]

SEVERITY_COLORS = {
    "critical": "#7c1d1d",
    "high": "#c0392b",
    "medium": "#e67e22",
    "low": "#f1c40f",
    "info": "#3498db",
}


def _sorted_findings(result: ScanResult):
    rank = {s.value: i for i, s in enumerate(SEVERITY_ORDER)}
    return sorted(result.findings, key=lambda f: rank.get(f.severity.value, 99))


def write_json(result: ScanResult, path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(result.to_dict(), fh, indent=2)
    return path


def write_html(result: ScanResult, path: str) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    counts = result.counts_by_severity()

    rows = []
    for f in _sorted_findings(result):
        color = SEVERITY_COLORS.get(f.severity.value, "#777")
        rows.append(
            f"""
            <tr>
              <td><span class="badge" style="background:{color}">{html.escape(f.severity.value.upper())}</span></td>
              <td>{html.escape(f.type)}</td>
              <td class="mono">{html.escape(f.endpoint)}</td>
              <td>{html.escape(f.parameter or '-')}</td>
              <td>{html.escape(f.description)}</td>
              <td class="mono">{html.escape(f.payload or '-')}</td>
              <td class="mono">{html.escape(f.evidence or '-')}</td>
            </tr>"""
        )

    summary_chips = "".join(
        f'<span class="chip" style="background:{SEVERITY_COLORS[s.value]}">'
        f'{s.value.upper()}: {counts[s.value]}</span>'
        for s in SEVERITY_ORDER
    )

    doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>WVS Report - {html.escape(result.target)}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background:#f4f6f8; color:#222; }}
  header {{ background:#1f2d3d; color:#fff; padding:24px 32px; }}
  header h1 {{ margin:0 0 4px; font-size:20px; }}
  header .target {{ font-family:monospace; opacity:.85; }}
  .wrap {{ padding:24px 32px; }}
  .score {{ font-size:42px; font-weight:700; }}
  .chip, .badge {{ color:#fff; padding:3px 10px; border-radius:12px; font-size:12px; font-weight:600; display:inline-block; }}
  .chip {{ margin-right:8px; }}
  table {{ width:100%; border-collapse:collapse; background:#fff; box-shadow:0 1px 3px rgba(0,0,0,.1); border-radius:8px; overflow:hidden; }}
  th, td {{ text-align:left; padding:10px 12px; border-bottom:1px solid #eee; vertical-align:top; font-size:13px; }}
  th {{ background:#fafbfc; font-size:12px; text-transform:uppercase; letter-spacing:.04em; color:#555; }}
  .mono {{ font-family:monospace; word-break:break-all; max-width:280px; }}
  .meta {{ color:#666; font-size:13px; margin:8px 0 20px; }}
  .empty {{ padding:24px; background:#fff; border-radius:8px; }}
</style>
</head>
<body>
<header>
  <h1>Web Vulnerability Scan Report</h1>
  <div class="target">{html.escape(result.target)}</div>
</header>
<div class="wrap">
  <div class="score">Risk score: {result.risk_score}/100</div>
  <div class="meta">
    Crawled {result.pages_crawled} page(s) &middot; {len(result.findings)} finding(s)
    &middot; {html.escape(result.started_at)} &rarr; {html.escape(result.finished_at)}
  </div>
  <div style="margin-bottom:20px">{summary_chips}</div>
  {_table_or_empty(rows)}
  <p class="meta">Generated by WVS. For authorized testing only.</p>
</div>
</body>
</html>"""

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(doc)
    return path


def _table_or_empty(rows: list) -> str:
    if not rows:
        return '<div class="empty">No findings. 🎉</div>'
    return f"""
    <table>
      <thead><tr>
        <th>Severity</th><th>Type</th><th>Endpoint</th><th>Param</th>
        <th>Description</th><th>Payload</th><th>Evidence</th>
      </tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>"""
